version: "3"
services:
  eureka-server:
   # 指定 Dockerfile文件路径
    build: .
    image: eureka-server:2.1.0
    container_name: eureka-server
    ports:
      - "8761:8761"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/data/docker/springcloud/eureka-server:/app:ro"
    command:
      - "-Xms256m"
      - "-Xmx256m"
      - "hk-discover-eureka-2.1.0.RELEASE.jar"
    restart: "always"
  springboot-admin:
    build: .
    image: springboot-admin:2.1.0
    container_name: springboot-admin
    ports:
      - "8780:8780"
    volumes:
      - "/etc/timezone:/etc/timezone"
      - "/etc/localtime:/etc/localtime:ro"
      - "/data/docker/springcloud/sprintboot-admin:/app:ro"
    command:
      - "-Xms256m"
      - "-Xmx256m"
      - "hk-springboot-admin-server-2.1.0.RELEASE.jar"
    restart: "always" 
  config-server:
    build: .
    image: config-server:2.1.0
    container_name: config-server
    ports:
      - "8770:8770"
    volumes:
      - "/etc/timezone:/etc/timezone"
      - "/etc/localtime:/etc/localtime:ro"
      - "/data/docker/springcloud/config-server:/app:ro"
    command:
      - "-Xms256m"
      - "-Xmx256m"
      - "hk-config-server-2.1.0.RELEASE.jar"
    restart: "always"
  oauth2-server:
    build: .
    image: oauth2-server
    container_name: oauth2-server
    ports:
      - "7100:7100"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/data/docker/springcloud/oauth2-server:/app:ro"
    command:
      - "-Xms256m"
      - "-Xmx256m"
      - "hk-sso-server-2.1.0.RELEASE.jar"
    restart: "always"
  
